name: gherkin
description: Gherkin parser/compiler for Dart.
version: 0.0.2
homepage: https://github.com/lamkr/cucumber-common

environment:
  sdk: '>=2.17.5 <3.0.0'

dependencies:
  #flutter:
  #  sdk: flutter
  #cupertino_icons: ^1.0.3

  characters: ^1.1.0
  meta: ^1.8.0
  path: ^1.8.2
  uuid: ^3.0.6

dev_dependencies:
  #flutter_test:
    #sdk: flutter
  lints: ^2.0.0
  test: ^1.21.4

flutter:
  assets:
    - assets/gherkin-languages.json

